@echo off
setlocal enabledelayedexpansion

cd /D "%~dp0"
cd ..

MKDIR artifacts > nul 2>&1
set FILENAME="artifacts\version.git.h.temp"

FOR /F "tokens=* USEBACKQ" %%F IN (`git rev-parse --abbrev-ref HEAD`) DO SET branch=%%F
FOR /F "tokens=* USEBACKQ" %%F IN (`git log "--pretty=format:%%h" -n 1`) DO SET shorthash=%%F
FOR /F "tokens=* USEBACKQ" %%F IN (`git describe --tags "--abbrev=0" --always`) DO SET latesttag=%%F
FOR /F "tokens=* USEBACKQ" %%F IN (`git rev-list HEAD --count`) DO SET revcount=%%F

REM echo #pragma once > %FILENAME%
echo // Automatically generated by git hook. Do not edit manually. > %FILENAME%
REM echo. >> %FILENAME%
echo #define GIT_BRANCH "%branch%" >> %FILENAME%
echo #define GIT_COMMIT "%latesttag%" >> %FILENAME%
echo #define GIT_REVCOUNT %revcount% >> %FILENAME%
echo #define GIT_SHORT_HASH "%shorthash%" >> %FILENAME%

set SOURCE_FILENAME="artifacts\version.git.h"
fc /W /L %FILENAME% %SOURCE_FILENAME% > nul 2>&1
if errorlevel 1 (
    copy %FILENAME% %SOURCE_FILENAME% /Y > nul
)


